### ISSUE TITLE
daily A&O on a wiki page

### ISSUE THREAD

**Issue by mess110** [dilcom/pilot-gnuplot#1]
Please provide daily Activities (for yesterday) & Objectives (for today) on a wiki page.

<Date>
- Acitivites:
  - activity1
  - activity2
  - etc
- Objectives:
  - objective1
  - objective2
  - etc

If you have ideas for a better format please use your idea :)

**Comment by ievgrafov** [comment]
@mess110 Sure, I think wikipages work good for that. Done.
Objectives are my goals and Activities are results, am I right?

**Comment by mess110** [comment]
@dilcom acitvities are what you did yesterday, objectives are what you are planning to do today

**Comment by agarie** [comment]
Hey @mess110, this is a very good idea. I'll try to read these whenever possible as well. :+1:
