### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by agisga** [dilcom/pilot-gnuplot#12]
I made a Matlab-like heatmap plot with `pilot-gnuplot`, from x, y, z Arrays.
However, I cannot figure out how to generate a heatmap from _a matrix of z-vales input_ (like in matlab), like for example shown [at gnuplotting.org here](http://www.gnuplotting.org/color-maps-and-the-scale-of-axes/). Is it possible?
I think, it would be very nice to include a heatmap example in /samples or /notebooks.

![Heatmap.png](http://dauns.math.tulane.edu/~agossman/pictures/heatmap.png)

I essentially used, with z = cos(0.5x^2+y^2):

``` Ruby
heatmap = Splot.new(
  [[x,y,z], with: 'image'],
  title: "Heatmap",
  style: 'data lines',
  palette: 'defined ( 0 "#000090",\
                      1 "#000fff",\
                      2 "#0090ff",\
                      3 "#0fffee",\
                      4 "#90ff70",\
                      5 "#ffee00",\
                      6 "#ff7000",\
                      7 "#ee0000",\
                      8 "#7f0000")',
  view: 'map',
  xrange: -PI..PI,
  yrange: -PI..PI
)
```

**Comment by ievgrafov** [comment]
Sure, here it is https://github.com/dilcom/pilot-gnuplot/blob/master/notebooks/heatmaps.ipynb

**Comment by agisga** [comment]
Nice!
My other question was if it is possible to plot from a data matrix, like for example done [here](http://www.gnuplotting.org/interpolation-of-heat-maps/) with:

```
set pm3d map
splot 'heat_map_data.txt' matrix
```

To be precise, I don't know how to pass `matrix` to `Splot` in pilot-gnuplot. I think this method is more familiar to people who have experience with Matlab (of course, it's also easy to just transform the data to x-y-z format).

**Comment by ievgrafov** [comment]
Oops, sorry, I missed it. Added this one too.

**Comment by agisga** [comment]
Cool :+1:
