### ISSUE TITLE
Dataset#update

### ISSUE THREAD

**Issue by agisga** [dilcom/pilot-gnuplot#13]
1. [Examples](https://github.com/dilcom/pilot-gnuplot/blob/master/lib/pilot-gnuplot/staff/dataset.rb#L91) in the comment to Dataset#update don't match the behaviour of the method.
   I think either the method definition should be `update(data: nil, **options)` (instead of `data = nil`), or the syntax in the examples should be `in_memory_points.update(some_update, title: 'Updated')` (instead of `data: some_update`).
2. I don't see the purpose of the line `temp_file_points = Dataset.new(points, title: 'Old one', file: true)` in the examples.
3. Additionally, if I do:

``` Ruby
> db = Datablock.new([1,2,3])
> d = Dataset.new(db)
> d.update([4,5,6])
=> #<Gnuplot::Dataset:0x007feed8c68e18
 @data=
  #<Gnuplot::Datablock:0x007feed8c683a0
   @data="1\n2\n34\n5\n6",
   @stored_in_file=false>,
 @options=Hamster::Hash[],
 @type=:datablock>
```

Shouldn't there be a "\n" in between 3 and 4, or do I understand something wrong?

**Comment by ievgrafov** [comment]
1-2. You're right, docs for Dataset#update is mix of correct examples and examples for Plot#update_dataset. Will fix it.
1. It's a bug. Thank you!
