### ISSUE TITLE
Examples from terminal.rb not working

### ISSUE THREAD

**Issue by agisga** [dilcom/pilot-gnuplot#16]
- The `#store_datablock` [example](https://github.com/dilcom/pilot-gnuplot/blob/master/lib/pilot-gnuplot/staff/terminal.rb#L48) yields `ArgumentError: No terminal given to output datablock [...]`
- [Example](https://github.com/dilcom/pilot-gnuplot/blob/master/lib/pilot-gnuplot/staff/terminal.rb#L97) given for `#set` does not produce the expected output.

**Comment by ievgrafov** [comment]
Thank you :+1: , fixed
