### ISSUE TITLE
Use time series plotting when daru is indexed on DateTimeIndex

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#24]
Daru's [DateTimeIndex class](https://github.com/v0dro/daru/blob/tseries/lib/daru/date_time/index.rb) labels time based data and lets users query it [using partial or complete date](https://github.com/v0dro/daru/blob/tseries/spec/date_time/data_spec.rb). The documentation isn't complete yet, but the tests should clarify any doubts you might have.

When a daru object is passed to Gnuplot, it would be great if Gnuplot auto-configured and used it's time series plotting functionality directly, without the need for manual configuration. Suggestions welcome!

Here's an example of a time series plot: ![Time Series Graph](http://i.stack.imgur.com/8ndjM.png).

Also, as pointed out by @agisga, here are the config options needed by GNU plot for configuring it to use time series: http://blog.mague.com/?p=201

@agarie @pjotrpr

**Comment by ievgrafov** [comment]
@v0dro  please take a look at [a notebook](https://github.com/dilcom/gnuplotrb/blob/master/notebooks/time_series_from_daru.ipynb). I put there examples with datetime indexes.

I also left there two error messages from daru. Maybe it'll be useful to fix this errors.

Defaults for datetime format will be added in next few days.

**Comment by v0dro** [comment]
Sure thanks. The Module::Tick error is strange. I'll try replicating it with a fresh installation.

Man that looks beautiful!

**Comment by v0dro** [comment]
I've pushed a commit to fix that Tick error - https://github.com/v0dro/daru/commit/21b4a77e2ccc192db62e7282ef9cc103e010ae31

Could you please verify if it works?

**Comment by v0dro** [comment]
Also, will it be possible for you to push all these notebooks to the [sciruby-notebooks repo](https://github.com/SciRuby/sciruby-notebooks) once they've reached a logical completion point?

It would keep everything in one place that way.

**Comment by ievgrafov** [comment]
I checked Tick error at latest code from your repository and everything is good :+1:

**Comment by v0dro** [comment]
@dilcom could you upload the notebooks on the [sciruby-notebooks repo](https://github.com/SciRuby/sciruby-notebooks) once they're complete?

**Comment by ievgrafov** [comment]
@v0dro no problem, I'll do it before GSoC end :+1:
