### ISSUE TITLE
Provide GnuplotRB with approximation mechanics

### ISSUE THREAD

**Issue by ievgrafov** [dilcom/pilot-gnuplot#27]
Gnuplot allows users to approximate given data with functions. It would be good if GnuplotRB offer an interface for such a feature.

**Comment by dilcom** [comment]
Add ranges for variables

**Comment by ievgrafov** [comment]
https://github.com/dilcom/gnuplotrb/commit/425a553d9728056c7e1eaaf023dc73ddbb89ca8b
https://github.com/dilcom/gnuplotrb/commit/589700973c322585d392c1064ac6318f6ce0300d
https://github.com/dilcom/gnuplotrb/commit/266d18b06a46f37b44e9299b1f6e50afcd082890
https://github.com/dilcom/gnuplotrb/commit/2d3dedaf2a6e7e4e4068db2f098ee38b82ecfd9f
https://github.com/dilcom/gnuplotrb/commit/dd68a7b7d12a138d7c8ffd095aff6c26525165dd

**Comment by ievgrafov** [comment]
https://github.com/dilcom/gnuplotrb/commit/3324614dfd84933f79e42ff484a2b535ca493b84
