### ISSUE TITLE
Line styles for line graphs

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#30]
Is it possible currently to set an option that will allow setting line styles for line graphs?

For example, a solid line with `'__'` or maybe a dotted line with `'...'` or a dashed line with `'---'`.

**Comment by ievgrafov** [comment]
@v0dro it's possible with 'dashtype' (or 'dt') option of dataset.
Examples:
Plot.new(['sin(x)', dt: '.. ']).plot # two dots and whitespace
Plot.new(['sin(x)', dt: '- ']).plot # dash and whitespace
Plot.new(['sin(x)', dt: '...']).plot # dots

I added dt to quoted options only in latest commit so in previous versions you should add quotes to pattern:
Plot.new(['sin(x)', dt: '".. "']).plot # two dots and whitespace

**Comment by v0dro** [comment]
Thanks!
