### ISSUE TITLE
#to_svg or #to_jpeg to save plot as an image

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#31]
It would be awesome to directly save the plot as an image by just saying `Plot#to_jpeg(file_name)` or the same for MultiPlot.

**Comment by ievgrafov** [comment]
Sure, I totally agree with you, and these methods are already implemented (I added them about 2 month ago), see [examples](https://github.com/dilcom/gnuplotrb/blob/master/examples/plot_to_image_file/plot.rb).

They work for Dataset, Plot, Splot and Multiplot.

**Comment by v0dro** [comment]
I cannot see any saved SVG file in my PWD when I do `Plot#to_svg('this_plot.svg')`.

**Comment by v0dro** [comment]
My bad sorry for that. Strange how I overlooked this in the docs.

**Comment by ievgrafov** [comment]
You can see it in docs [here](http://www.rubydoc.info/gems/gnuplotrb/GnuplotRB%2FPlottable%3Ato_specific_term).

This methods are handled by #method_missing and depend on gnuplot installation (e.g. if gnuplot has 'cairopng' terminal, #to_cairopng method will exist) so I have no idea how to add them to docs as separate methods.

**Comment by v0dro** [comment]
No wonder :\

You can use the YARD syntax. I've done that in daru [here](https://github.com/v0dro/daru/blob/master/lib/daru/maths/statistics/dataframe.rb#L67).

Adding them somewhere inside the relevant class will force YARD to render a method when there is really is no method written.

**Comment by ievgrafov** [comment]
I already tried this with RDoc's :method: directive and it seems to be the same as @!method in YARD. I'll again add several common methods like #to_svg and hide others deep in the docs because most of them are generated dynamically and I can't predict if user will have some of them or not.

**Comment by v0dro** [comment]
Would it possible to create a common interface and raise errors if a particular method is not available?

**Comment by ievgrafov** [comment]
It's done this way now =). When you call #to_|terminal_name| it searches for the terminal and raises an error if not found.

I'll dive into YARD syntax and document this case better. Thank you :+1:. Feedbacks are very helpful

**Comment by v0dro** [comment]
Btw it would also be helpful to write about GNU plot specific stuff in the README so that people who have already not used GNU plot before (like me) don't need to dive into GNU plot docs before using your gem.

For example I have no idea what a terminal means in case of GNU plot.

**Comment by mess110** [comment]
A link in README.md should suffice. GNUplot has many features and it can be a tedious task to explain a lot of these concepts, which are already documented. The goal for the gem documentation should be to teach the user how to "translate" from gnuplot syntax to ruby syntax and provide examples.

**Comment by v0dro** [comment]
^agreed.

**Comment by ievgrafov** [comment]
I will provide readme with rules of translation, short list of capabilities and links to gnuplot doc. Of course I can't cover all gnuplot features with my docs and for some information one should dive into gnuplot docs anyway
