### ISSUE TITLE
Better configuration for multiplot

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#32]
Currently I'm using the following code with a daru dataframe to plot each Vector on a different sub-plot in a Multiplot:

``` ruby

plots = []
data_frame.each_vector_with_index do |vec,n|
  plots << Plot.new([vec, with: 'lines', title: n])
end

Multiplot.new(*plots, layout: [3,1], title: 'Rolling sums')
```

This produces a plot that looks like this:
![plot](https://cloud.githubusercontent.com/assets/2629909/9014360/8c6ce302-37df-11e5-9402-9bc823695912.jpg)

I found it pretty hard to configure multiplot to create a series 3 plots stacked on top of each other that share a common X axis at the bottom.

Something like this:
![](http://i.stack.imgur.com/FHDS2.png)

To do this how about having a DSL that would go something like:

``` ruby

Multiplot.new(many, plots, and, options) do |mp|
  mp.title = "Some title"
  mp.layout = [2,3]
  plots = mp.yield_plots
  plots[0].upper_margin = 0
  # etc.
end

# Please dont let my ignorance of the GNU Plot API get in the way here.
```

[Here](http://stackoverflow.com/questions/19131509/multiplot-stacking-3-graphs-on-a-larger-canvas) is an SO answer relating to stacking graphs.

This might be related to #29

**Comment by ievgrafov** [comment]
@v0dro this really seems reasonable to me so I added bunch of destructive methods (they end with '!' or '=') which change state of the object. So now you can use something like:

```
Multiplot.new(many, plots, and, options).tap do |mp|
  mp.title = "Some title"
  mp.layout = [2,3]
  mp[0].upper_margin = 0
  # etc.
end
```

::new methods still don't yield block so one should use '#tap' in such cases.

Changes are also bad tested now so you may face bugs. I'll test and document it up to next release.

**Comment by v0dro** [comment]
Awesome!

**Comment by v0dro** [comment]
Could you please include this API in the notebook?

**Comment by ievgrafov** [comment]
Sure, I left here a little note for you and going to document it up to end of the next week (including notebook and in-code docs).
