### ISSUE TITLE
Multiplot not respecting date format of individual plots

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#34]
Here's my code:

``` ruby

# pieces is an Array of Daru::DataFrame objects indexed on DateTimeIndex.
plots = []
pieces.each do |df|
  plot = GnuplotRB::Plot.new([df['births'], with: 'lines', title: df['name'][0]])
  plot.format_x("%Y")
  plots << plot
end
GnuplotRB::Multiplot.new(*plots, layout: [2,2])
```

When I plot an individual plot the date format is correct (only year), and I expect the same for multiplot, but instead I get this:
![screenshot from 2015-08-07 19 53 25](https://cloud.githubusercontent.com/assets/2629909/9137881/4f8d9846-3d3e-11e5-9450-d0e65dae89ee.png)

**Comment by ievgrafov** [comment]
Hm, when you set option using `#<some_option_name>` it creates and returns a new object with this option set. It does not affect existing object. If you want to change state of existing object, you should use destructive methods (ending with ! or =). Just as you do it with Array#sort and Array#sort!. Examples:

``` ruby
plots = []
pieces.each do |df|
  plot = GnuplotRB::Plot.new([df['births'], with: 'lines', title: df['name'][0]])
  plot.format_x = '%Y' # or plot.format_x!('%Y')
  plots << plot
end
GnuplotRB::Multiplot.new(*plots, layout: [2,2])
```

You can also set format_x option for multiplot and it will affect all nested plots:

``` ruby
plots = pieces.map do |df| # sorry if pieces is not Enumerable
  GnuplotRB::Plot.new([df['births'], with: 'lines', title: df['name'][0]])
end
GnuplotRB::Multiplot.new(*plots, layout: [2,2], format_x: '%Y')
```

**Comment by v0dro** [comment]
I tried both those methods right now and none are working.

EDIT: Its working with the latest development release.

**Comment by ievgrafov** [comment]
Oops, yes, I added destructive methods after v0.3.0.

But second version (pass  format_x to `Multiplot::new`) should work for v0.3.0 too. Will check it. You can also pass this options to `Plot::new`: `Plot.new([df['births'], with: 'lines', title: df['name'][0]], format_x: '%Y')`.
