### ISSUE TITLE
Plottable#plot freezes

### ISSUE THREAD

**Issue by Zhomart** [dilcom/pilot-gnuplot#35]
Sometimes it works. Now it stopped working for the same dataset.

It freezes here https://github.com/dilcom/gnuplotrb/blob/master/lib%2Fgnuplotrb%2Fplot.rb#L87

**Comment by ievgrafov** [comment]
@Zhomart couldn't you please provide me with the dataset and the code you're using? Probably it's an issue in options handling and I need more details to dig into it.

**Comment by Zhomart** [comment]
@dilcom Here is the dataset

``` ruby
ds_ary = [
  [ [[0, 0, 700, 700, 1250], [0, 800, 0, 800, 0]], {:with=>"points", :title=>"Border", :linestyle=>{:pointtype=>1, :ps=>2}} ],
]

GnuplotRB::Plot.new(*ds_ary).to_png("a.png")
```

This code worked several days ago, I don't know what did I change, now it doesn't work.

Other info

```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

gem 'gnuplotrb', github: 'SciRuby/gnuplotrb'
```

**Comment by Zhomart** [comment]
Wait, it started working. This line was incorrect `:linestyle=>{:pointtype=>1, :ps=>2}`.
Initially I put it because `gnuplotrb` didn't work, and I wanted to play with other gem `gnuplot`.
Now it works!

Thank you! I'll re-open this issue if it stops working again.
