### ISSUE TITLE
OptionHandling.option

### ISSUE THREAD

**Issue by agisga** [dilcom/pilot-gnuplot#8]
The method [`option`](https://github.com/dilcom/pilot-gnuplot/blob/master/lib/pilot-gnuplot/mixins/option_handling.rb#L123) appears to be broken. I tried to call `plot.option('title')`, `plot.option('title', 'New Title')`, `plot.option(title: 'New Title')` on a `Plot` object, but all of these either give an ArgumentError or have no effects on anything.

Additionally, the documentation/comment given for `option` does not represent the method, rather it describes a different method `options`.

**Comment by ievgrafov** [comment]
Oops, I forgot to remove docs and make this method private. I suggest you to use `plot.title('New title')` instead of `plot.option(:title, 'New title')`. Thank you, I'll fix docs and list of private methods.

**Comment by agisga** [comment]
Oh, it totally is not broken. I misunderstood how the method is supposed to be used, my bad.

**Comment by mess110** [comment]
@agisga thx for the catch though. I just copied the example code and it worked. That extra s got me :P

**Comment by ievgrafov** [comment]
Method worked not as mentioned in docs so I think it was broken =), my fault
